name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions!
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from ${{ github.event_name }}!"
      - run: echo "The job is running on ${{ runner.os }}."
      - run: echo "The name of your branch is ${{ github.ref }}."
      - run: echo "The repo is ${{ github.repository }}."
      - name: Check out repo code
        uses: actions/checkout@v3
      - name: List files
        run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}"